### ISSUE TITLE
Update Docker

### ISSUE THREAD

**Issue by jcorreia11** [BioSystemsUM/DeepMol#100]
The provided Docker is not up to date.

We should update the Dockerfile with the current requirements so Docker users can easily use DeepMol.

**Comment by jcapels** [comment]
@jcorreia11 I think this is solved... we already have an image on dockerhub: https://hub.docker.com/r/biosystemsum/deepmol/tags

**Comment by jcapels** [comment]
@jcorreia11 can we close this?

**Comment by jcorreia11** [comment]
yes!
