### ISSUE TITLE
Class Dataset does not have get_task_names method

### ISSUE THREAD

**Issue by jcorreia11** [BioSystemsUM/DeepMol#16]
`get_task_names` method used for instance in the `output_predictions` method of the `Evaluator` class is not implemented in the `Dataset` or child classes.

This method or an alternative should be implemented.

**Comment by jcapels** [comment]
How will this be after the Dataset refactoring?

**Comment by jcorreia11** [comment]
Sorry, I just saw this. This will be fixed in the Dataset refactoring.
