### ISSUE TITLE
Feature_Selection Error

### ISSUE THREAD

**Issue by Juliyan96** [BioSystemsUM/DeepMol#28]
Dear João, 

I have been encountering an attribute error with the feature_selection. I have attached the code below for your reference along with the error. 

**Code:** 

```
from boruta.boruta_py import BorutaPy
from deepmol.feature_selection.base_feature_selector import BorutaAlgorithm
from deepmol.compound_featurization import MorganFingerprint
from deepmol.loaders.loaders import CSVLoader
from deepmol.feature_selection import LowVarianceFS
from deepmol.splitters.splitters import SingletaskStratifiedSplitter
from deepmol.models.sklearn_models import SklearnModel
from deepmol.metrics.metrics import Metric
from deepmol.metrics.metrics_functions import roc_auc_score, precision_score, accuracy_score, confusion_matrix, classification_report
from deepmol.parameter_optimization.hyperparameter_optimization import HyperparameterOptimizerValidation
from deepmol.imbalanced_learn.imbalanced_learn import SMOTEENN
import numpy as np
from deepmol.standardizer.custom_standardizer import CustomStandardizer, heavy_standardisation

standardizer2 = CustomStandardizer(heavy_standardisation).standardize(dataset)
dataset = CSVLoader(dataset_path='/content/drive/MyDrive/2. Dataset_Deepmol.csv', mols_field='Smiles', labels_fields='Class', id_field='ID')
dataset = dataset.create_dataset()
dataset.get_shape()

dataset = MorganFingerprint().featurize(dataset)
print(dataset.X)
print(dataset.y)
print(dataset.mols)
print(dataset.get_shape())

dataset = LowVarianceFS(0.1).featureSelection(dataset)
```
**Error:**
AttributeError                            Traceback (most recent call last)
[<ipython-input-31-072b769d0f30>](https://localhost:8080/#) in <module>
----> 1 dataset = LowVarianceFS(0.1).featureSelection(dataset)

AttributeError: 'LowVarianceFS' object has no attribute 'featureSelection'

Kindly help me in resolving this issue.
Thanks

**Comment by jcorreia11** [comment]
Hi Juliyan, the tutorials on the README need to be updated. Sorry about that. 
The method to perform feature selection is now called `select_features` instead of `featureSelection`.

So you need to do `LowVarianceFS(0.1).select_features(dataset)`.

We are currently doing some refactoring of the package so it could be expected that other things may change in the next versions.

Hope my answer helps you.
Best regards,
João Correia

**Comment by Juliyan96** [comment]
Dear João,
The method you suggested worked. Thank you for your time.
Regards, 
Juliyan
