### ISSUE TITLE
Cannot import featurizers for Deepchem

### ISSUE THREAD

**Issue by Juliyan96** [BioSystemsUM/DeepMol#33]
Dear Joao, 

I have tried making a neural network-based model using the deepmol and deepchem packages. However, I have difficulty with importing the featurization module. I believe you have made changes that have not been updated. Kindly advise me on how to resolve the matter. I have attached the code and the error message below.

Code:
```
from deepchem.models import GraphConvModel
from deepmol.models.deepchem_models import DeepChemModel
from deepmol.metrics.metrics import Metric
from deepmol.splitters.splitters import SingletaskStratifiedSplitter
from deepmol.compound_featurization import ConvMolFeat
```
Error:

ImportError                               Traceback (most recent call last)
[<ipython-input-19-4e5c0cc81000>](https://localhost:8080/#) in <module>
      3 from deepmol.metrics.metrics import Metric
      4 from deepmol.splitters.splitters import SingletaskStratifiedSplitter
----> 5 from deepmol.compound_featurization import ConvMolFeat

ImportError: cannot import name 'ConvMolFeat' from 'deepmol.compound_featurization' (/usr/local/lib/python3.8/dist-packages/deepmol/compound_featurization/__init__.py)

**Comment by jcapels** [comment]
Hi, this problem has been fixed and you can use it as is in the tutorial by upgrading the package.

`pip install deepmol[all]==0.0.4.1b0`
