### ISSUE TITLE
Import error for parameter optimization

### ISSUE THREAD

**Issue by Juliyan96** [BioSystemsUM/DeepMol#35]
Dear Joao, 
I have been getting an import error with the hyperparameter optimization module with the import code that had been provided in the tutorial. I also checked the modules individually to see what the issue might be. Can you kindly guide me through this? But with my previous work with the package it worked. I am wondering why there is this sudden error. I have provided the code and the error message here.
Thanks

Code:
`from deepmol.parameter_optimization.hyperparameter_optimization import HyperparameterOptimizerValidation
`
Error:
ImportError                               Traceback (most recent call last)
[<ipython-input-16-4a32823ff25f>](https://localhost:8080/#) in <module>
----> 1 from deepmol.parameter_optimization.hyperparameter_optimization import HyperparameterOptimizerValidation

1 frames
[/usr/local/lib/python3.8/dist-packages/deepmol/parameter_optimization/hyperparameter_optimization.py](https://localhost:8080/#) in <module>
     19 from deepmol.models import SklearnModel, KerasModel
     20 from deepmol.models.models import Model
---> 21 from deepmol.parameter_optimization import DeepchemRandomSearchCV, DeepchemGridSearchCV
     22 
     23 

ImportError: cannot import name 'DeepchemRandomSearchCV' from partially initialized module 'deepmol.parameter_optimization' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/deepmol/parameter_optimization/__init__.py)

**Comment by jcapels** [comment]
Hi, 

We just deployed version 0.0.4.2b0, which addresses this issue. Moreover, PR #39 fixed this issue and was merged into the master branch.

Thank you for your feedback, it is very much appreciated.
