### ISSUE TITLE
Error on Neural Network analysis

### ISSUE THREAD

**Issue by Juliyan96** [BioSystemsUM/DeepMol#36]
Dear Joao, 
I have been getting error messages frequently in making a neural network. However, everything seems to work except when printing out the results. Previously it worked. But I believe it is because of the recent update on the package. I have provided the code here. Please guide me on how to resolve the issue. I want to point out that this worked previously when I used the old package for neural networks. This issue only seems to be when working with neural networks and not sklearn models.

Code:
```
from deepmol.loaders.loaders import CSVLoader
from deepchem.models import GraphConvModel
from deepmol.models.deepchem_models import DeepChemModel
from deepmol.metrics.metrics import Metric
from deepmol.metrics.metrics_functions import roc_auc_score, precision_score, accuracy_score, confusion_matrix, classification_report
from deepmol.splitters.splitters import SingletaskStratifiedSplitter
from deepmol.compound_featurization import ConvMolFeat

ds = ConvMolFeat().featurize(dataset)
splitter = SingletaskStratifiedSplitter()
train_dataset, valid_dataset, test_dataset = splitter.train_valid_test_split(dataset=ds, frac_train=0.7, frac_valid=0.3,
                                                                             frac_test=0)

graph = GraphConvModel(n_tasks=1, mode='classification')
model_graph = DeepChemModel(graph)

model_graph.fit(train_dataset)
valid_preds = model_graph.predict(valid_dataset)

metrics = [Metric(roc_auc_score), Metric(precision_score), Metric(accuracy_score), Metric(confusion_matrix), 
           Metric(classification_report)]
print('Training Dataset: ')
train_score = model_graph.evaluate(train_dataset, metrics)
```
Error:
Training Dataset: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-35-f9c94783b617> in <module>
      2            Metric(classification_report)]
      3 print('Training Dataset: ')
----> 4 train_score = model_graph.evaluate(train_dataset, metrics)

2 frames
/usr/local/lib/python3.8/dist-packages/deepchem/models/models.py in evaluate(self, dataset, metrics, transformers, per_task_metrics, use_sample_weights, n_classes)
    213     """
    214     evaluator = Evaluator(self, dataset, transformers)
--> 215     return evaluator.compute_model_performance(
    216         metrics,
    217         per_task_metrics=per_task_metrics,

/usr/local/lib/python3.8/dist-packages/deepchem/utils/evaluate.py in compute_model_performance(self, metrics, csv_out, stats_out, per_task_metrics, use_sample_weights, n_classes)
    297           "Stats output is not written; please manually write output instead")
    298     # Process input metrics
--> 299     metrics = _process_metric_input(metrics)
    300 
    301     y = self.dataset.y

/usr/local/lib/python3.8/dist-packages/deepchem/utils/evaluate.py in _process_metric_input(metrics)
    110       final_metrics.append(wrap_metric)
    111     else:
--> 112       raise ValueError(
    113           "metrics must be one of metric function / dc.metrics.Metric object /"
    114           "list of dc.metrics.Metric or metric functions.")

ValueError: metrics must be one of metric function / dc.metrics.Metric object /list of dc.metrics.Metric or metric functions.

**Comment by jcapels** [comment]
Hi, 

We just deployed version 0.0.4.2b0, which addresses this issue. Moreover, PR #39 fixed this issue and was merged into the master branch.

Thank you for your feedback, it is very much appreciated.
